### ISSUE TITLE
fix: support < v10.1.0-next.6 library projects

### ISSUE THREAD

**Issue by chihab** [ngworker/angular-versions-action#20]
## Describe the bug

Starting from Angular v10.1.0-next.6, the library builder has changed:
```diff
-"builder": "@angular-devkit/build-ng-packagr:build",
+"builder": "@angular-devkit/build-angular:ng-packagr",
```

This causes library builds on versions prior to v10.1.0-next.6 to fail since we're targeting a builder that does not exist.

Failing pipeline:
https://github.com/chihab/ngx-access/actions/runs/703138676

ng-packagr builder update: v10.1.0-next.6
https://github.com/angular/angular-cli/commit/da9825ceb279807eb65f6cff65e5da83209d9d2a#diff-15ae6659598d4085a6e89c51399950e056dddc736a2c78a0affd515d9feae072

## To Reproduce

Besides the action execution above, I run the action locally  (replaced the @actions/core with static values) on a Angular 11.x project
```diff
-  const angularVersion: string = core.getInput('angular-version');
+ const angularVersion: string = process.argv[2];
```

`node ../angular-versions-action/dist/index.js 10.0.x`

`package.json` dependencies update looks okay.
![image](https://user-images.githubusercontent.com/196852/113118807-b855f700-9207-11eb-94f4-7acc55712ff4.png)

`npm install && npm run build`
![image](https://user-images.githubusercontent.com/196852/113124745-c27af400-920d-11eb-9283-c232ccd6bda6.png)

## Expected behavior

I expect the library to build successfully 😀

## Possible solutions

In Lumberjack you seem to have the deprecated builder name as a dependency which explains why it works with the action. So either:

Solution1 (for any Angular version): 
 - Add the legacy builder dependency in package.json
 - Replace the library builder in `angular.json`

Solution2 (for "legacy" Angular versions):
 - Add the legacy builder dependency in package.json
 - Update `angular.json` according to the target angular version.

**Comment by LayZeeDK** [comment]
By the way, to use `core.getInput('angular-version')` locally, I think you need to set an environment variable such as `INPUT_ANGULAR_VERSION=10.0.x`. Do you remember if this is right, @NachoVazquez?

**Comment by NachoVazquez** [comment]
> By the way, to use `core.getInput('angular-version')` locally, I think you need to set an environment variable such as `INPUT_ANGULAR_VERSION=10.0.x`. Do you remember if this is right, @NachoVazquez?

I think that's the way, it varies on Windows, Mac, and Linux I think

**Comment by LayZeeDK** [comment]
We have come up with a plan for fixing this. As we need to touch `angular.json`, we're going to introduce breaking changes and release this bugfix as part of v4.0.

**Comment by LayZeeDK** [comment]
@chihab
Please use the `v4` tag to fix this issue.
```yml
- uses: ngworker/angular-versions-action@v4
  with:
    # or any other supported version
    angular-version: 12.0.x
    # (optional parameter) the workspace root folder containing `package.json` and `angular.json`
    root-path: ./
```

**Comment by chihab** [comment]
Thank you @NachoVazquez!

**Comment by NachoVazquez** [comment]
> Thank you @NachoVazquez!

Thank you @chihab ! Now the Action is better after your suggestion. Awesome!
